package store

const (
	CollectionAuditLogs                    = "admin_audit_logs"
	CollectionCharacters                   = "characters"
	CollectionConstellations               = "constellations"
	CollectionCorporations                 = "corporations"
	CollectionGates                        = "gates"
	CollectionIntelChannels                = "intel_channels"
	CollectionIntelReportHash              = "intel_report_hashes"
	CollectionIntelReports                 = "intel_reports"
	CollectionIntelUploaders               = "intel_uploaders"
	CollectionJumpbridges                  = "jumpbridges"
	CollectionAlliances                    = "alliances"
	CollectionAllowedAlliances             = "allowed_alliances"
	CollectionAllowedCorporations          = "allowed_corporations"
	CollectionMoons                        = "moons"
	CollectionPlanets                      = "planets"
	CollectionRegions                      = "regions"
	CollectionSDEMeta                      = "sde_meta"
	CollectionSiteAnnouncements            = "site_announcements"
	CollectionSolarSystems                 = "solar_systems"
	CollectionSovereigntyCampaignWatchlist = "sovereignty_campaign_watchlist"
	CollectionTopRoutes                    = "top_routes"
	CollectionTimers                       = "timers"
	CollectionUploaderSessions             = "uploader_sessions"
	CollectionUploaderTokens               = "uploader_tokens"
	CollectionUsers                        = "users"
)
